README.md
_nx_cugraph/__init__.py
nx_cugraph/tests/test_ego_graph.py

> Keep the nx-cugraph repo in sync with any relevant changes made to the cugraph codebase
Part of https://github.com/rapidsai/graph_dl/issues/578
This PR updates branch-24.12 with any updates that were made since the last fast-forward ([PR on Oct 3, 2024](https://github.com/rapidsai/nx-cugraph/pull/4))
This was done by running `git log --since="2024-10-03" --name-only --pretty=format: -- python/nx-cugraph/ | sort | uniq` inside the cugraph repo to see which files were modified since the last fast-forward.
These files were then copied over while preserving their history
```bash
git filter-repo \
--path python/nx-cugraph/_nx_cugraph/__init__.py \
--path python/nx-cugraph/nx_cugraph/tests/test_ego_graph.py \
--path python/nx-cugraph/README.md \
--path-rename …
```

Merge fast-forwarded files from cugraph into nx-cugraph

---

.github/labeler.yml
.github/workflows/build.yaml
.github/workflows/test.yaml
.gitignore
.pre-commit-config.yaml
build.sh
ci/release/update-version.sh
dependencies.yaml
print_env.sh

Proposes another batch of changes to get this repo ready to become the primary home of `nx-cugraph` development.
* removes some unnecessary configuration leftover from the `cugraph` repo
* updates CI configs
* adds a `ci/update-release.sh` script (which RAPIDS ops will use when cutting new releases)
* updates all pre-commit hooks to their latest versions
I'll leave more comments inline.

remove more cugraph-only details, other miscellaneous build/packaging changes

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.pre-commit-config.yaml
_nx_cugraph/__init__.py
benchmarks/nx-cugraph/pytest-based/bench_algos.py
benchmarks/nx-cugraph/pytest-based/create_results_summary_page.py
ci/build_python.sh
ci/run_nx_cugraph_pytests.sh
ci/test_python.sh
ci/test_wheel_nx-cugraph.sh
ci/wheel_smoke_test_nx-cugraph.py
dependencies.yaml
docs/nx-cugraph/source/sphinxext/github_link.py
notebooks/cugraph_benchmarks/nx_cugraph_benchmark.ipynb
nx_cugraph/__init__.py
nx_cugraph/algorithms/bipartite/generators.py
nx_cugraph/algorithms/community/louvain.py
nx_cugraph/algorithms/core.py
nx_cugraph/algorithms/link_analysis/hits_alg.py
nx_cugraph/algorithms/shortest_paths/generic.py
nx_cugraph/algorithms/shortest_paths/unweighted.py
nx_cugraph/algorithms/traversal/breadth_first_search.py
nx_cugraph/convert_matrix.py
nx_cugraph/interface.py
nx_cugraph/utils/decorators.py
pyproject.toml

Closes https://github.com/rapidsai/graph_dl/issues/638
Adds CI workflows running the unit tests.
Also adds some `.pre-commit-config.yaml` changes, follow-up to #14 suggested by @eriknw .
I copied these new scripts in `ci/` from the latest state of `branch-24.12` in https://github.com/rapidsai/cugraph, then tried to adapt them to be `nx-cugraph` specific.
Proposing we add notebook tests in a follow-up PR, to keep things smaller and easier to review.

add CI workflows running tests

---

.github/workflows/build.yaml

Closes https://github.com/rapidsai/graph_dl/issues/647
Updates `build.yaml` to enable building & publishing packages from this repo.
Scripts are copied from `build.yaml` from branch-24.12 in https://github.com/rapidsai/cugraph.

Add `nx-cugraph` Package Publishing

---

ci/build_python.sh
ci/test_python.sh
nx_cugraph/algorithms/core.py

Within this release, `nx-cugraph` moved from https://github.com/rapidsai/cugraph to this repo.
To avoid conflicts between nightlies produced from the different sources, CI scripts here were hard-coding the version for CI artifacts to `24.12.00a1000`. That should be removed now that this is the only repo packages are being published from (should have been removed in #16, sorry for missing it).

remove versioning workaround for nightlies

---

.github/labeler.yml

Remove automatic "Python" labeler

---

benchmarks/nx-cugraph/pytest-based/bench_algos.py
nx_cugraph/algorithms/shortest_paths/unweighted.py
nx_cugraph/algorithms/shortest_paths/weighted.py

Closes https://github.com/rapidsai/graph_dl/issues/631
For larger graphs, nearly all the time is spent creating dicts of lists of paths. This PR delays creating the lists of paths by duck-typing the return object and returning a Mapping that computes paths as needed. There is virtually no performance penalty for this, and a huge performance gain by delaying computation.
Moved from here: https://github.com/rapidsai/cugraph/pull/4739

Faster `shortest_path`

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/cuda11.8-conda/devcontainer.json
.devcontainer/cuda11.8-pip/devcontainer.json
.devcontainer/cuda12.5-conda/devcontainer.json
.devcontainer/cuda12.5-pip/devcontainer.json
.github/workflows/pr.yaml

Adds devcontainers and devcontainer CI jobs.
I created this by copying from the `cugraph` repo and then just changing all the references to `nx-cugraph` (and removing a few unnecessary things, like details about cloning cugraph-ops).
This will be blocked until https://github.com/rapidsai/devcontainers/pull/417 or https://github.com/rapidsai/devcontainers/pull/418 is merged.

add devcontainers

---

.devcontainer/Dockerfile
.devcontainer/cuda11.8-conda/devcontainer.json
.devcontainer/cuda11.8-pip/devcontainer.json
.devcontainer/cuda12.5-conda/devcontainer.json
.devcontainer/cuda12.5-pip/devcontainer.json
.github/workflows/pr.yaml
ci/release/update-version.sh

Contributes to https://github.com/rapidsai/build-planning/issues/118
Proposes the following changes for pip devcontainers:
* use UCX 1.17 (ref: https://github.com/rapidsai/cugraph-gnn/pull/79#discussion_r1861029925)
* prefer system installation of ucx to the one provided by the `libucx-cu{11,12}` wheels (ref: https://github.com/rapidsai/devcontainers/pull/421#issuecomment-2502324982)
And some other related changes noticed while doing that:
* update lingering `24.*` references to `25.02`
* fix `update-version.sh` so those will be correctly updated in future releases
Similar to https://github.com/rapidsai/cugraph/pull/4792
Relying on CI for most things. But for `update-version.sh`, tested like this:
```shell
./ci/release/update-version.sh '25.02.00'
git grep -E '24\.'
```

prefer system install of UCX in devcontainers, update outdated RAPIDS references

---

CHANGELOG.md
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml

This pinning was needed for [historical reasons that are no longer relevant](https://github.com/rapidsai/cucim/pull/481/commits/5cbc80b3a7fa49f25959674d3a97e6d8cf503fcb).

Remove sphinx pinning

---

benchmarks/pytest-based/bench_algos.py

This PR adds a newly added benchmark dataset to `bench_algos.py`

Add `amazon0302` Dataset to nx-cugraph Bench Algos

---

.devcontainer/cuda11.8-pip/devcontainer.json
.devcontainer/cuda12.5-pip/devcontainer.json
.pre-commit-config.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/138
Updates to using UCX 1.18 in pip devcontainers here.
Also updates to the latest version of `rapids-dependency-file-generator` in `pre-commit` config.

update pip devcontainers to UCX 1.18, other small packaging changes

---

benchmarks/pytest-based/bench_algos.py
benchmarks/pytest-based/run-main-benchmarks.sh

Here are results from a single round of benchmarks for louvain and leiden:
```
Name (time in ms)                                                                 Min
bench_leiden_communities[ds=karate-backend=cugraph-preconverted]              32.3493
bench_louvain_communities[ds=karate-backend=cugraph-preconverted]             15.2782
bench_leiden_communities[ds=netscience-backend=cugraph-preconverted]          83.5688
bench_louvain_communities[ds=netscience-backend=cugraph-preconverted]         34.1273
bench_leiden_communities[ds=email_Eu_core-backend=cugraph-preconverted]       81.3393
bench_louvain_communities[ds=email_Eu_core-backend=cugraph-preconverted]      50.0181
bench_leiden_communities[ds=amazon0302-backend=cugraph-preconverted]         755.0755 …
```

Add benchmark for `leiden_communities`

---

README.md
_nx_cugraph/__init__.py
benchmarks/pytest-based/bench_algos.py
nx_cugraph/algorithms/__init__.py
nx_cugraph/algorithms/link_prediction.py
nx_cugraph/classes/graph.py
nx_cugraph/tests/test_link_prediction.py

Adds support for `jaccard_coefficient` to nx-cugraph.
This includes a test, but relies largely on the existing test coverage provided by NetworkX. The test included here could (should) be submitted to NetworkX though in a separate PR, since it is not covering anything unique to nx-cugraph.
A benchmark is also included, with results showing 2-4X speedup. I've seen much, much larger speedup on a different graph (large movie review bipartite graph, showing 966s for NX, 2s for nx-cugraph = ~500X), so I need to investigate further.  This investigation need not prevent this PR from being merged now though.

Adds support for `jaccard_coefficient`

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

This PR points the shared workflow branches back to the default 25.02 branches.
xref: https://github.com/rapidsai/build-planning/issues/139

Revert CUDA 12.8 shared workflow branch changes

---

.devcontainer/cuda12.8-conda/devcontainer.json
.devcontainer/cuda12.8-pip/devcontainer.json
.github/workflows/pr.yaml
README.md
_nx_cugraph/__init__.py
benchmarks/pytest-based/bench_algos.py
benchmarks/pytest-based/run-main-benchmarks.sh
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml
nx_cugraph/algorithms/__init__.py
nx_cugraph/algorithms/link_prediction.py
nx_cugraph/classes/graph.py
nx_cugraph/tests/test_link_prediction.py

Manual forward merge from 25.02 to 25.04. This PR should not be squashed.

Forward-merge branch-25.02 to branch-25.04

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

This migrates amd64 CI jobs (PRs and nightlies) to use L4 GPUs from the NVKS cluster.
xref: https://github.com/rapidsai/build-infra/issues/184

Migrate to NVKS for amd64 CI runners

---

notebooks/demo/nx_cugraph_jaccard_movie_recommender.ipynb

This PR adds a notebook to demonstrate nx-cugraph's support for `nx.jaccard_coefficients()` by implementing a simple movie recommendation system based on MovieLens data.
This notebook will also be made available in Google Colab and referenced in an upcoming blog.

Adds notebook for Jaccard Similarity

---

nx_cugraph/algorithms/bipartite/generators.py
nx_cugraph/convert.py
nx_cugraph/convert_matrix.py
nx_cugraph/generators/classic.py
nx_cugraph/generators/small.py
nx_cugraph/tests/test_generators.py
nx_cugraph/tests/test_match_api.py
nx_cugraph/utils/decorators.py

This should help give better log messages when `create_using` is an instance of a networkx graph, since we can't update an nx graph inplace.

Add `can_run` that checks `create_using` argument

---

CHANGELOG.md
nx_cugraph/algorithms/centrality/betweenness.py
nx_cugraph/tests/test_bc.py

I'd like to understand why `edge_betweenness_centrality` needs to scale results to match networkx when `k` is given. Is PLC or NetworkX doing it wrong? My guess is that NetworkX is actually incorrect this time.

Update BC to use random nodes to match nx given `k`

---

ci/build_wheel.sh
ci/test_wheel_nx-cugraph.sh

Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```

Use `rapids-pip-retry` in CI jobs that might need retries

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

This completes the migration to NVKS runners now that all libraries have been tested and https://github.com/rapidsai/shared-workflows/pull/273 has been merged.
xref: https://github.com/rapidsai/build-infra/issues/184

Use shared-workflows branch-25.04

---

.pre-commit-config.yaml
ci/build_wheel.sh
ci/release/update-version.sh
ci/test_python.sh
ci/test_wheel_nx-cugraph.sh
ci/validate_wheel.sh

`shellcheck` is a fast, static analysis tool for shell scripts. It's good at
flagging up unused variables, unintentional glob expansions, and other potential
execution and security headaches that arise from the wonders of `bash` (and
other shlangs).
This PR adds a `pre-commit` hook to run `shellcheck` on all of the `sh-lang`
files in the `ci/` directory, and the changes requested by `shellcheck` to make
the existing files pass the check.
xref: rapidsai/build-planning#135

Add `shellcheck` to pre-commit and fix warnings

---

.pre-commit-config.yaml
benchmarks/pytest-based/create_results_summary_page.py
pyproject.toml

It's been a few months since we've updated these.
Also, I reached for "Maintenance" label, which I think makes sense for PRs like this, but didn't find it.

Update pre-commit hooks

---

nx_cugraph/classes/digraph.py
nx_cugraph/classes/multidigraph.py
nx_cugraph/scripts/print_tree.py
nx_cugraph/tests/test_classes.py
scripts/update_readme.py

Regression test added. `__networkx_cache__` should be a `_GraphCache` object to ensure the graph remains valid.
I double-checked to make sure all graph classes are calling the appropriate init of super classes when created.
Also, I fixed a potential infinite loop in `scripts/update_readme.py`.

Fix `(Multi)DiGraph.__networkx_cache__` initialization

---

_nx_cugraph/__init__.py
nx_cugraph/algorithms/centrality/betweenness.py

Update note about `betweenness_centrality`, because libcugraph was updated to match  https://github.com/networkx/networkx/pull/7908, but does not yet match https://github.com/networkx/networkx/pull/7949.

Update docs for BC

---

CHANGELOG.md

Following RAPIDS maintainer guides [here](https://docs.rapids.ai/maintainers/forward-merger/) because it seems that there is a change blocking https://github.com/rapidsai/nx-cugraph/pull/117 from being merged.

Branch 25.06 merge 25.04 (Trying Again)

---

conda/recipes/nx-cugraph/recipe.yaml

This quotes `head_rev` to ensure that commits with leading zeros in the git SHA include those zeros in the output package name.
xref: https://github.com/rapidsai/build-planning/issues/176

Quote head_rev in conda recipes

---

.devcontainer/cuda12.8-conda/devcontainer.json
.devcontainer/cuda12.8-pip/devcontainer.json
.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
CONTRIBUTING.md
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml

This PR reverts shared-workflows branches to `branch-25.06` and ensures builds use CUDA 12.8.
CUDA 12.9 will be used in the test matrix but not for builds in RAPIDS 25.06. See https://github.com/rapidsai/build-planning/issues/173#issuecomment-2882179838 for more information.

Finish CUDA 12.9 migration and use branch-25.06 workflows

---

ci/build_python.sh
ci/build_wheel.sh
ci/build_wheel_nx-cugraph.sh

Contributes to https://github.com/rapidsai/build-planning/issues/181
* removes all uploads of conda packages and wheels to `downloads.rapids.ai`
Looked for uses of the relevant `gha-tools` tools, as well as documentation about `downloads.rapids.ai`, being on the NVIDIA VPN, using S3, etc. like this:
```shell
git grep -i -E 's3|upload|downloads\.rapids|vpn'
```
See "How I tested this" on https://github.com/rapidsai/shared-workflows/pull/364

stop uploading packages to downloads.rapids.ai

---

benchmarks/pytest-based/README.md
benchmarks/pytest-based/get_graph_bench_dataset.py
benchmarks/pytest-based/run-main-benchmarks.sh

This makes it easier to run benchmarks, by respecting the default value of `${RAPIDS_DATASET_ROOT_DIR}` if defined in the user's environment.
I also made minor improvements to the benchmarking docs.

Use environment as default for RAPIDS_DATASET_ROOT_DIR, improve benchmark docs

---

.pre-commit-config.yaml
ci/test_python.sh
nx_cugraph/algorithms/centrality/betweenness.py
nx_cugraph/drawing/layout.py
nx_cugraph/tests/pytest.ini
run_nx_tests.sh

This PR temporarily unblocks CI by skipping tests that rely on `path_graph`, which currently has a bug in nx-cugraph.
#160 should fix those bugs and re-enable the tests.

Temporarily skip certain tests to unblock CI

---

.devcontainer/cuda12.9-conda/devcontainer.json
.devcontainer/cuda12.9-pip/devcontainer.json
.github/workflows/pr.yaml
conda/environments/all_cuda-129_arch-aarch64.yaml
conda/environments/all_cuda-129_arch-x86_64.yaml
dependencies.yaml

Addressing issues:
* https://github.com/rapidsai/build-planning/issues/195
* https://github.com/rapidsai/build-planning/issues/173
Use CUDA 12.9 throughout different build and test environments.

Use CUDA 12.9 in Conda, Devcontainers, Spark, GHA, etc.

---

benchmarks/pytest-based/bench_algos.py

Catch `CUDARuntimeError` in the benchmarks when checking for a GPU and treat it as no GPU is available.

Catch `CUDARuntimeError` in CuPy GPU check

---

.github/labeler.yml
.github/workflows/labeler.yaml

Bumps the version of `actions/labeler` to `@v5` and updates the syntax in
the `labeler.yml` file to account for breaking changes in that version bump.
xref: rapidsai/ops#2968

ci(labeler): update labeler action to @v5
